version: '3'

services:
  jupyterlab-gpu:
    image: jupyterlab-gpu:3.10.9
    container_name: jupyterlab-gpu
    runtime: nvidia
    user: 1000:1000
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONPATH=
    volumes:
      - ${HOME}:/home/host # MOUNT_HOST_HOME
      - ${HOME}/.jupyterlab/jupyterlab-gpu:/home # MOUNT_JUPYTER_HOME
      - ../jupyter-settings/jupyter_user_settings:/home/jupyter/.jupyter/lab/user-settings # MOUNT_JUPYTER_USER_SETTINGS
      - ../jupyter-settings/jupyter_notebook_config.py:/home/jupyter/.jupyter/jupyter_notebook_config.py # MOUNT_JUPYTER_NOTEBOOK_SETTINGS
      - ../jupyter-settings/ipython_config.py:/home/jupyter/.ipython/profile_default/ipython_config.py # MOUNT_IPYTHON_SETTINGS
      - ../jupyter-settings/ptpython_config.py:/home/jupyter/.config/ptpython/config.py # MOUNT_PTPYTHON_SETTINGS
      - ../jupyter-settings/bashrc:/home/jupyter/.bashrc # MOUNT_BASHRC
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    tty: true
    entrypoint: >
      jupyter-lab
        --allow-root
        --ip=0.0.0.0 --port=${PORT}
        --no-browser
        --NotebookApp.token=''
        --NotebookApp.password=''
        --NotebookApp.disable_check_xsrf=True
