version: '3'

services:
  jupyterlab-gpu:
    image: jupyterlab-gpu:3.10.9
    container_name: jupyterlab-gpu
    runtime: nvidia
    user: 1000:1000
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONPATH=
    volumes:
      - ${MOUNT_HOST_HOME}
      - ${MOUNT_JUPYTER_HOME}
      - ${MOUNT_JUPYTER_USER_SETTINGS}
      - ${MOUNT_JUPYTER_NOTEBOOK_SETTINGS}
      - ${MOUNT_IPYTHON_SETTINGS}
      - ${MOUNT_PTPYTHON_SETTINGS}
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    tty: true
    entrypoint: >
      jupyter-lab
        --allow-root
        --ip=0.0.0.0 --port=${PORT}
        --no-browser
        --NotebookApp.token=''
        --NotebookApp.password=''
        --NotebookApp.disable_check_xsrf=True
