version: '3'

services:
  jupyterlab:
    image: jupyterlab:latest
    container_name: 'jupyterlab'
    user: 1000:1000
    restart: always
    env_file:
      - env_file.env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER=${USER}
    working_dir: /home
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - ${MOUNT_HOST_HOME}
      - ${MOUNT_JUPYTER_HOME}
      - ${MOUNT_JUPYTER_USER_SETTINGS}
      - ${MOUNT_JUPYTER_NOTEBOOK_SETTINGS}
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    tty: true
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0 --port=${PORT}
      --no-browser
      --NotebookApp.token=''
      --NotebookApp.password=''
      --NotebookApp.disable_check_xsrf=True
