version: '3'

services:
  jupyterlab:
    image: jupyterlab:3.11.1
    container_name: jupyterlab
    user: 1000:1000
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BASE_IMAGE=cn47/jupyterlab:3.11.1
    environment:
      - PYTHONPATH=
    volumes:
      - ${HOME}:/home/host # MOUNT_HOST_HOME
      - ${HOME}/.jupyterlab/jupyterlab:/home # MOUNT_JUPYTER_HOME
      - ../jupyter-settings/jupyter_user_settings:/home/jupyter/.jupyter/lab/user-settings # MOUNT_JUPYTER_USER_SETTINGS
      - ../jupyter-settings/jupyter_notebook_config.py:/home/jupyter/.jupyter/jupyter_notebook_config.py # MOUNT_JUPYTER_NOTEBOOK_SETTINGS
      - ../jupyter-settings/ipython_config.py:/home/jupyter/.ipython/profile_default/ipython_config.py # MOUNT_IPYTHON_SETTINGS
      - ../jupyter-settings/ptpython_config.py:/home/jupyter/.config/ptpython/config.py # MOUNT_PTPYTHON_SETTINGS
      - ../jupyter-settings/bashrc:/home/jupyter/.bashrc # MOUNT_BASHRC
    expose:
      - ${PORT-:8888}
    ports:
      - ${PORT-:8888}:${PORT-:8888}
    tty: true
    entrypoint: >
      jupyter-lab
        --allow-root
        --ip=0.0.0.0 --port=${PORT-:8888}
        --no-browser
        --NotebookApp.token=''
        --NotebookApp.password=''
        --NotebookApp.disable_check_xsrf=True
