version: '3'

services:
  python3:
    image: python3:3.11.1
    container_name: 'python3'
    user: 1000:1000
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        _HOME=${HOME}
    environment:
      - LANG=ja_JP.UTF-8
      - LANGUAGE=ja_JP:ja
      - LC_ALL=ja_JP.UTF-8
      - TZ=Asia/Tokyo
      - TERM=xterm-256color
      - PYTHONUTF8=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - PIP_DISABLE_PIP_VERSION_CHECK=on
      - PIP_NO_CACHE_DIR=off
    working_dir: /opt
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - ${HOME}:${HOME}
      - ./opt:/opt
    tty: true
    command: ptpython
