version: '3'

services:
  python3:
    image: python3:3.9.10
    container_name: 'python3'
    user: 1000:1000
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - env_file.env
    working_dir: /opt
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - ${HOME}:${HOME}
      - ./opt:/opt
    tty: true
    command: ptpython
